image: python:alpine

before_script:
  - pip install -r server/requirements.txt
  - pip install -r server/requirements-dev.txt

test:
  script:
    - cd server
    - python -m unittest
    - coverage run -m unittest
    - coverage report -m
